smtp_on: false
smtp_host: dagbne16.bne.local
smtp_hostbackup: ''
smtp_port: '25'
smtp_protocol: standard
smtp_autotls: false
smtp_timeout: 30
smtp_username: ''
smtp_password: ''
smtp_from: administrador@bne.es
smtp_fromname: ''
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '1'
smtp_test_address: ''
smtp_debugging: true
prev_mail_system: php_mail
smtp_keepalive: true
_core:
  default_config_hash: 2v5R3I9tNatGzKQjuZWh1y_955xK09313Vn-IIuedyI
langcode: es
