tmgmt.translator.settings.plata_eu:
  type: mapping
  mapping:
    auto_accept:
      type: boolean
      label: Automatically accept
    url:
      type: string
      label: Remote URL, used for tests.
    api_key:
      type: string
      label: API key
